from dataclasses import dataclass
from typing import Optional

GAME_NAME = "Resident Evil 0"

@dataclass(frozen=True)
class ItemDef:
    name: str
    code: int
    count: int
    classification: str
    area_index: Optional[int] = None
    notes: str = ""

@dataclass(frozen=True)
class LocationDef:
    name: str
    code: int
    region: str
    vanilla_item: str
    description: str
    kind: str = "normal"
    notes: str = ""
    area_index: int = 0

LOCATION_DEFS = [
    LocationDef('Train - Engine Cab - Ammo Under Cabinet', 47001000, 'Engine Cab', 'Handgun Ammo x15', 'Under the cabinet in the Engine Cab.', 'normal', '', 0),
    LocationDef('Train - Engine Cab - Ammo Northeast Corner', 47001002, 'Engine Cab', 'Handgun Ammo x15', 'In the northeast corner of the Engine Cab.', 'normal', '', 0),
    LocationDef("Train - Officer's Car - Dining Car Key", 47001003, 'Train Start', 'Dining Car Key', "The vanilla Dining Car Key pickup in the Officer's Car.", 'scripted', 'Live capture shows inventory item ID 103.', 0),
    LocationDef("Train - Officer's Car - Edward Ammo", 47001004, 'Train Start', 'Handgun Ammo x15', "On Edward's body after he bursts through the window.", 'spawned', '', 0),
    LocationDef('Train - Cabin 201 - Ink Ribbon', 47001005, 'Train Start', 'Ink Ribbon x3', 'On the table next to the typewriter.', 'normal', '', 0),
    LocationDef('Train - Cabin 201 - Green Herb', 47001006, 'Train Start', 'Green Herb', 'On the floor next to the bunk beds.', 'normal', '', 0),
    LocationDef('Train - Cabin 202 - Ink Ribbon', 47001007, 'Train Start', 'Ink Ribbon x1', 'Inside the jacket hanging next to the bunk beds.', 'normal', '', 0),
    LocationDef('Train - Cabin 202 - Handgun Ammo', 47001008, 'Train Start', 'Handgun Ammo x15', 'On the floor in Cabin 202.', 'normal', '', 0),
    LocationDef("Train - Conductor's Office - Green Herb", 47001009, 'Conductor Wing', 'Green Herb', 'On the window ledge opposite the entrance.', 'normal', '', 0),
    LocationDef("Train - Conductor's Office - Red Herb", 47001010, 'Conductor Wing', 'Red Herb', 'On the window ledge opposite the entrance.', 'normal', '', 0),
    LocationDef("Train - Conductor's Office - Briefcase", 47001011, 'Conductor Wing', 'Briefcase', 'Inside the closet in the southeast corner.', 'normal', '', 0),
    LocationDef('Train - Dining Car - Empty Bottle', 47001012, 'Dining / Service', 'Empty Bottle x3', 'On the floor in the fridge after the zombie bursts out.', 'spawned', '', 0),
    LocationDef('Train - Freight Car - Gold Ring', 47001013, 'Freight / Rear', 'Gold Ring', 'On the floor of the second kennel in the northeast corner.', 'normal', '', 0),
    LocationDef('Train - Freight Car - First-Aid Spray', 47001014, 'Freight / Rear', 'First-Aid Spray', 'On the shelf in the northwest corner.', 'normal', '', 0),
    LocationDef('Train - Freight Car - Shotgun Ammo', 47001015, 'Freight / Rear', 'Shotgun Ammo x7', 'On the shelf in the northwest corner.', 'normal', '', 0),
    LocationDef('Train - Freight Car - Gas Tank', 47001016, 'Freight / Rear', 'Gas Tank x3', 'On the floor next to the shelf in the middle of the car.', 'normal', '', 0),
    LocationDef('Train - Rear Carriage - Hookshot', 47001017, 'Freight / Rear', 'Hookshot', 'The native two-slot Hookshot pickup in the rear carriage.', 'two_slot', '', 0),
    LocationDef('Train - Bar Lounge - Panel Opener', 47001018, 'Conductor Wing', 'Panel Opener', 'Among the wreckage on the west side after defeating Stinger.', 'boss_reward', '', 0),
    LocationDef('Train - Upstairs Passenger Car - Green Herb', 47001019, 'Conductor Wing', 'Green Herb', 'On the table next to the phone.', 'normal', '', 0),
    LocationDef('Train - Upstairs Passenger Car - Ice Pick', 47001020, 'Conductor Wing', 'Ice Pick', 'On the small trolley next to the west entrance.', 'normal', '', 0),
    LocationDef('Train - Cabin 101 - First-Aid Spray', 47001021, 'Conductor Wing', 'First-Aid Spray', 'In the sink in the northeast corner.', 'normal', '', 0),
    LocationDef('Train - Cabin 101 - Ink Ribbon', 47001022, 'Conductor Wing', 'Ink Ribbon x3', 'On the floor next to the desk in the northwest corner.', 'normal', '', 0),
    LocationDef('Train - Cabin 101 - Handgun Ammo', 47001023, 'Conductor Wing', 'Handgun Ammo x30', 'On the floor in the southeast corner.', 'normal', '', 0),
    LocationDef('Train - Cabin 101 - Shotgun Ammo', 47001024, 'Conductor Wing', 'Shotgun Ammo x7', 'On the floor in the southeast corner.', 'normal', '', 0),
    LocationDef('Train - Cabin 101 - Hunting Gun', 47001025, 'Conductor Wing', 'Hunting Gun', 'The native two-slot Hunting Gun pickup in Cabin 101.', 'two_slot', '', 0),
    LocationDef('Train - Cabin 102 - Knife', 47001026, 'Cabin 102', 'Knife', 'On the floor in the middle of the room.', 'normal', '', 0),
    LocationDef('Train - Cabin 102 - Jewelry Box', 47001027, 'Cabin 102', 'Jewelry Box', 'On the floor of the closet in the northeast corner.', 'container', 'Examining the Jewelry Box gives the vanilla Silver Ring.', 0),
    LocationDef('Train - Service Room - Green Herb', 47001029, 'Dining / Service', 'Green Herb', 'On the bench next to the service lift in the southwest corner.', 'normal', '', 0),
    LocationDef('Train - Service Room - Handgun Ammo', 47001030, 'Dining / Service', 'Handgun Ammo x15', 'On the bench on the north side.', 'normal', '', 0),
    LocationDef("Train - Service Room - Conductor's Key", 47001031, 'Dining / Service', "Conductor's Key", "The vanilla Conductor's Key pickup in the Service Room.", 'scripted', 'Live capture shows inventory item ID 65.', 0),
    LocationDef('Facility - Main Hall - Ink Ribbon', 47002100, 'Facility Early', 'Ink Ribbon x3', 'Static record 91; room 36.', 'normal', '', 1),
    LocationDef('Facility - Main Hall - Green Herb', 47002101, 'Facility Early', 'Green Herb', 'Static record 92; room 36.', 'normal', '', 1),
    LocationDef('Facility - Main Hall - Red Herb', 47002102, 'Facility Early', 'Red Herb', 'Static record 93; room 36.', 'normal', '', 1),
    LocationDef('Facility - Main Hall - Handgun Ammo', 47002103, 'Facility Early', 'Handgun Ammo x15', 'Static record 94; room 36.', 'normal', '', 1),
    LocationDef('Facility - Dining Room - Handgun Ammo', 47002104, 'Facility Early', 'Handgun Ammo x15', 'Static record 101; room 37.', 'normal', '', 1),
    LocationDef('Facility - Kitchen - Lighter Fluid', 47002117, 'Facility Fire', 'Lighter Fluid', 'Static record 102; room 38.', 'normal', '', 1),
    LocationDef('Facility - Kitchen - Empty Bottle', 47002118, 'Facility Fire', 'Empty Bottle x3', 'Static record 103; room 38.', 'normal', '', 1),
    LocationDef('Facility - Projection Room - Handgun Ammo', 47002124, 'Facility Clock', 'Handgun Ammo x30', 'Static record 106; room 39.', 'normal', '', 1),
    LocationDef('Facility - Bathroom - Green Herb', 47002121, 'Facility Early', 'Green Herb', 'Static record 127; room 41.', 'normal', '', 1),
    LocationDef('Facility - Bathroom - Gas Tank', 47002122, 'Facility Early', 'Gas Tank x6', 'Static record 128; room 41.', 'normal', '', 1),
    LocationDef('Facility - Bathroom - Empty Bottle', 47002123, 'Facility Early', 'Empty Bottle x3', 'Static record 129; room 41.', 'normal', '', 1),
    LocationDef('Facility - Boiler Room - Green Herb 1', 47002142, 'Facility Basement', 'Green Herb', 'Static record 130; room 42. Post-statue scale / restored-power steam-clear access.', 'normal', '', 1),
    LocationDef('Facility - Boiler Room - Green Herb 2', 47002143, 'Facility Basement', 'Green Herb', 'Static record 131; room 42. Post-statue scale / restored-power steam-clear access.', 'normal', '', 1),
    LocationDef('Facility - Boiler Room - Blue Herb', 47002144, 'Facility Basement', 'Blue Herb', 'Static record 132; room 42. Post-statue scale / restored-power steam-clear access.', 'normal', '', 1),
    LocationDef('Facility - Boiler Room - Red Herb', 47002145, 'Facility Basement', 'Red Herb', 'Static record 133; room 42. Post-statue scale / restored-power steam-clear access.', 'normal', '', 1),
    LocationDef('Facility - Observatory Tower - Handgun Ammo', 47002178, 'Facility MO', 'Handgun Ammo x30', 'Static record 134; room 43.', 'normal', '', 1),
    LocationDef('Facility - Storage Room - Shotgun', 47002127, 'Facility Early', 'Shotgun', 'Static record 141; room 44.', 'normal', '', 1),
    LocationDef('Facility - Storage Room - Black Statue', 47002128, 'Facility Early', 'Black Statue', 'Static record 142; room 44.', 'normal', '', 1),
    LocationDef('Facility - Storage Room - Gas Tank', 47002129, 'Facility Early', 'Gas Tank x6', 'Static record 143; room 44.', 'normal', '', 1),
    LocationDef('Facility - Entrance - Discipline Tablet', 47002177, 'Facility Crank', 'Discipline Tablet', 'Static record 149; room 45.', 'normal', '', 1),
    LocationDef('Facility - Fountain Area - Green Herb', 47002114, 'Facility Crank', 'Green Herb', 'Static record 150; room 45.', 'normal', '', 1),
    LocationDef('Facility - Fountain Area - Red Herb', 47002115, 'Facility Crank', 'Red Herb', 'Static record 151; room 45.', 'normal', '', 1),
    LocationDef('Facility - Lecture Room - Ink Ribbon', 47002105, 'Facility MO', 'Ink Ribbon x3', 'Static record 153; room 47.', 'normal', '', 1),
    LocationDef('Facility - Lecture Room - Shotgun Ammo', 47002106, 'Facility MO', 'Shotgun Ammo x7', 'Static record 154; room 47.', 'normal', '', 1),
    LocationDef('Facility - Medicine Room - First-Aid Spray', 47002130, 'Facility MO', 'First-Aid Spray', 'Static record 163; room 49.', 'normal', '', 1),
    LocationDef('Facility - Medicine Room - Blue Herb 1', 47002131, 'Facility MO', 'Blue Herb', 'Static record 164; room 49.', 'normal', '', 1),
    LocationDef('Facility - Medicine Room - Blue Herb 2', 47002132, 'Facility MO', 'Blue Herb', 'Static record 165; room 49.', 'normal', '', 1),
    LocationDef('Facility - Main Library - Microfilm A', 47002107, 'Facility Crank', 'Microfilm A', 'Static record 169; room 50.', 'normal', '', 1),
    LocationDef('Facility - Clock Room - Handgun Ammo', 47002108, 'Facility Crank', 'Handgun Ammo x15', 'Static record 170; room 50.', 'normal', '', 1),
    LocationDef('Facility - Main Library - Ink Ribbon', 47002109, 'Facility Crank', 'Ink Ribbon x3', 'Static record 171; room 50.', 'normal', '', 1),
    LocationDef('Facility - Assistant Director Office - Handgun Ammo', 47002111, 'Facility Fire', 'Handgun Ammo x15', 'Static record 173; room 51.', 'normal', '', 1),
    LocationDef('Facility - Assistant Director Office - Shotgun Ammo', 47002113, 'Facility Fire', 'Shotgun Ammo x7', 'Static record 175; room 51.', 'normal', '', 1),
    LocationDef('Facility - Small Library - Grenades', 47002119, 'Facility Library', 'Grenades x6', 'Static record 180; room 52.', 'normal', '', 1),
    LocationDef('Facility - Small Library - Book of Good', 47002120, 'Facility Library', 'Book of Good', 'Static record 181; room 52.', 'normal', '', 1),
    LocationDef('Facility - Marcus Office - Handgun Ammo', 47002133, 'Facility MO', 'Handgun Ammo x15', 'Static record 188; room 54.', 'normal', '', 1),
    LocationDef('Facility - Marcus Office - Ink Ribbon', 47002134, 'Facility MO', 'Ink Ribbon x3', 'Static record 189; room 54.', 'normal', '', 1),
    LocationDef('Facility - Marcus Office - Napalm Grenades', 47002135, 'Facility MO', 'Napalm Grenades x6', 'Static record 190; room 54.', 'normal', '', 1),
    LocationDef('Facility - Private Study - Microfilm B', 47002125, 'Facility Clock', 'Microfilm B', 'Static record 203; room 56.', 'normal', '', 1),
    LocationDef('Facility - Private Study - Shotgun Ammo', 47002126, 'Facility Clock', 'Shotgun Ammo x7', 'Static record 205; room 56.', 'normal', '', 1),
    LocationDef('Facility - Art Room - Grenade Launcher', 47002137, 'Facility Crank', 'Grenade Launcher', 'Static record 208; room 57.', 'normal', '', 1),
    LocationDef('Facility - Art Room - White Statue', 47002138, 'Facility Crank', 'White Statue', 'Static record 209; room 57.', 'normal', '', 1),
    LocationDef('Facility - Art Room - Shotgun Ammo', 47002139, 'Facility Crank', 'Shotgun Ammo x7', 'Static record 210; room 57.', 'normal', '', 1),
    LocationDef('Facility - Old Laboratory - First-Aid Spray', 47002166, 'Facility Water', 'First-Aid Spray', 'Static record 243; room 60.', 'normal', '', 1),
    LocationDef('Facility - Old Laboratory - Empty Bottle', 47002167, 'Facility Water', 'Empty Bottle x3', 'Static record 244; room 60.', 'normal', '', 1),
    LocationDef('Facility - Old Laboratory - Green Herb', 47002168, 'Facility Water', 'Green Herb', 'Static record 245; room 60.', 'normal', '', 1),
    LocationDef('Facility - Old Laboratory - Red Herb', 47002169, 'Facility Water', 'Red Herb', 'Static record 246; room 60.', 'normal', '', 1),
    LocationDef('Facility - Old Laboratory - Handgun Ammo', 47002170, 'Facility Water', 'Handgun Ammo x15', 'Static record 247; room 60.', 'normal', '', 1),
    LocationDef('Facility - Maintenance Room - Obedience Tablet', 47002171, 'Facility Water', 'Obedience Tablet', 'Static record 250; room 61.', 'normal', '', 1),
    LocationDef('Facility - Maintenance Room - Shotgun Ammo', 47002172, 'Facility Water', 'Shotgun Ammo x7', 'Static record 251; room 61.', 'normal', '', 1),
    LocationDef('Facility - Piano Bar - Battery', 47002173, 'Facility Water', 'Battery', 'Static record 252; room 62.', 'normal', '', 1),
    LocationDef('Facility - Piano Bar - Magnum Ammo', 47002174, 'Facility Water', 'Magnum Ammo x8', 'Static record 253; room 62.', 'normal', '', 1),
    LocationDef('Facility - Piano Bar - Empty Bottle', 47002175, 'Facility Water', 'Empty Bottle x3', 'Static record 254; room 62.', 'normal', '', 1),
    LocationDef('Facility - Broadcast Room - Vise Handle', 47002176, 'Facility Water', 'Vise Handle', 'Static record 260; room 63.', 'normal', '', 1),
    LocationDef('Facility - Outside Balcony - Green Herb 1', 47002140, 'Facility Water', 'Green Herb', 'Static record 269; room 64.', 'normal', '', 1),
    LocationDef('Facility - Outside Balcony - Green Herb 2', 47002141, 'Facility Water', 'Green Herb', 'Static record 270; room 64.', 'normal', '', 1),
    LocationDef('Facility - Large Hall - Fire Key', 47002116, 'Facility Crank', 'Fire Key', 'Static record 276; room 65.', 'normal', '', 1),
    LocationDef('Facility - Assistant Director Office - Iron Needle', 47002112, 'Facility Fire', 'Iron Needle', 'Inventory/scripted pickup in room 51.', 'scripted', '', 1),
    LocationDef('Facility - Marcus Office - Book of Evil', 47002136, 'Facility MO', 'Book of Evil', 'Inventory/scripted pickup in room 54.', 'scripted', '', 1),
    LocationDef('Basement - Monitor Room - Handgun Ammo 1', 47002146, 'Facility Basement', 'Handgun Ammo x15', 'Static record 286; room 87.', 'normal', '', 1),
    LocationDef('Basement - Monitor Room - Handgun Ammo 2', 47002147, 'Facility Basement', 'Handgun Ammo x15', 'Static record 287; room 87.', 'normal', '', 1),
    LocationDef('Basement - Monitor Room - Handgun Ammo 3', 47002148, 'Facility Basement', 'Handgun Ammo x15', 'Static record 288; room 87.', 'normal', '', 1),
    LocationDef('Basement - Monitor Room - Gas Tank', 47002149, 'Facility Basement', 'Gas Tank x6', 'Static record 289; room 87.', 'normal', '', 1),
    LocationDef('Basement - Monitor Room - Shotgun Ammo', 47002150, 'Facility Basement', 'Shotgun Ammo x7', 'Static record 290; room 87.', 'normal', '', 1),
    LocationDef('Basement - Observation Room - Ink Ribbon', 47002151, 'Facility Basement', 'Ink Ribbon x3', 'Static record 299; room 89.', 'normal', '', 1),
    LocationDef('Basement - Observation Room - Green Herb', 47002152, 'Facility Basement', 'Green Herb', 'Static record 300; room 89.', 'normal', '', 1),
    LocationDef('Basement - Observation Room - Blue Herb', 47002153, 'Facility Basement', 'Blue Herb', 'Static record 301; room 89.', 'normal', '', 1),
    LocationDef('Basement - Statue Room - Handgun Ammo x5', 47002154, 'Facility Basement', 'Handgun Ammo x5', 'Static record 309; room 90.', 'normal', '', 1),
    LocationDef('Basement - Storage Room - Ink Ribbon', 47002155, 'Facility Basement', 'Ink Ribbon x3', 'Static record 311; room 91.', 'normal', '', 1),
    LocationDef('Basement - Bunk Room A - Unity Tablet', 47002156, 'Facility Basement', 'Unity Tablet', 'Static record 315; room 93.', 'normal', '', 1),
    LocationDef('Basement - Bunk Room A - Empty Bottle', 47002157, 'Facility Basement', 'Empty Bottle x3', 'Static record 316; room 93.', 'normal', '', 1),
    LocationDef('Basement - Waterfall Room - Locker Key', 47002158, 'Facility Basement', 'Locker Key', 'Static record 320; room 94.', 'normal', '', 1),
    LocationDef('Basement - Training Room - Water Key', 47002159, 'Facility Basement', 'Water Key', 'Static record 325; room 96.', 'normal', '', 1),
    LocationDef('Basement - Training Room - Acid Grenades', 47002160, 'Facility Basement', 'Acid Grenades x6', 'Static record 326; room 96.', 'normal', '', 1),
    LocationDef('Basement - Training Room - Handgun Ammo 1', 47002161, 'Facility Basement', 'Handgun Ammo x15', 'Static record 327; room 96.', 'normal', '', 1),
    LocationDef('Basement - Training Room - Handgun Ammo 2', 47002162, 'Facility Basement', 'Handgun Ammo x15', 'Static record 328; room 96.', 'normal', '', 1),
    LocationDef('Basement - Training Room - Shotgun Ammo', 47002163, 'Facility Basement', 'Shotgun Ammo x7', 'Static record 329; room 96.', 'normal', '', 1),
    LocationDef('Basement - Training Room - Magnum Ammo x1', 47002164, 'Facility Basement', 'Magnum Ammo x1', 'Static record 330; room 96.', 'normal', '', 1),
    LocationDef('Basement - Training Room - Duralumin Case', 47002165, 'Facility Basement', 'Duralumin Case', 'Inventory/scripted locker pickup in room 96.', 'scripted', '', 1),
    LocationDef('Lab - Outside Area - Red Herb', 47003100, 'Lab Start', 'Red Herb', 'Static record 344.', 'normal', '', 2),
    LocationDef('Lab - Machine Room 1F - Output Regulator Coil', 47003101, 'Lab Machine', 'Output Regulator Coil', 'Static record 347; first/randomizable coil only.', 'normal', '', 2),
    LocationDef('Lab - Elevator Passage - Green Herb', 47003102, 'Lab Start', 'Green Herb', 'Static record 349.', 'normal', '', 2),
    LocationDef('Lab - Elevator Passage - Red Herb', 47003103, 'Lab Start', 'Red Herb', 'Static record 350.', 'normal', '', 2),
    LocationDef('Lab - Machine Room 2F - Ink Ribbon', 47003104, 'Lab Start', 'Ink Ribbon x3', 'Static record 367.', 'normal', '', 2),
    LocationDef('Lab - Machine Room 2F - Shotgun Ammo', 47003105, 'Lab Start', 'Shotgun Ammo x7', 'Static record 368.', 'normal', '', 2),
    LocationDef('Lab - Machine Room 2F - Empty Bottle', 47003106, 'Lab Start', 'Empty Bottle x3', 'Static record 369.', 'normal', '', 2),
    LocationDef('Lab - Machine Room 2F - Green Herb', 47003107, 'Lab Start', 'Green Herb', 'Static record 370.', 'normal', '', 2),
    LocationDef('Lab - Machine Room 2F - Gas Tank', 47003108, 'Lab Start', 'Gas Tank x3', 'Static record 371.', 'normal', '', 2),
    LocationDef('Lab - Leech Laboratory - Breeding Room Key', 47003109, 'Lab Sterile', 'Breeding Room Key', 'Static record 375.', 'normal', '', 2),
    LocationDef('Lab - Leech Laboratory - Shotgun Ammo', 47003110, 'Lab Sterile', 'Shotgun Ammo x7', 'Static record 377.', 'normal', '', 2),
    LocationDef("Lab - Marcus' Private Room - Green Leech Charm", 47003111, 'Lab Marcus', 'Green Leech Charm', 'Static record 380.', 'normal', '', 2),
    LocationDef('Lab - Operating Room - First-Aid Spray', 47003112, 'Lab Start', 'First-Aid Spray', 'Static record 385.', 'normal', '', 2),
    LocationDef('Lab - Morgue - Handgun Ammo A', 47003114, 'Lab Morgue', 'Handgun Ammo x15', 'Static record 390.', 'normal', '', 2),
    LocationDef('Lab - Morgue - Handgun Ammo B', 47003115, 'Lab Morgue', 'Handgun Ammo x15', 'Static record 391.', 'normal', '', 2),
    LocationDef('Lab - Breeding Room - Dial', 47003116, 'Lab Breeding', 'Dial', 'Static record 394 in the Breeding Room.', 'normal', '', 2),
    LocationDef('Lab - Leech Room - Gas Tank', 47003117, 'Lab Start', 'Gas Tank x6', 'Static record 397.', 'normal', '', 2),
    LocationDef('Lab - Leech Room - Empty Bottle', 47003118, 'Lab Start', 'Empty Bottle x3', 'Static record 398.', 'normal', '', 2),
    LocationDef('Lab - Cable Car - Magnum', 47003119, 'Lab Machine', 'Magnum', 'Static record 403; normal AP location with the Dial-specific self-lock restriction.', 'normal', '', 2),
    LocationDef('Lab - Reference Room - Ink Ribbon', 47003120, 'Lab Start', 'Ink Ribbon x3', 'Static record 405.', 'normal', '', 2),
    LocationDef("Lab - Marcus's Study - Handgun Ammo", 47003121, 'Lab Marcus', 'Handgun Ammo x15', 'Static record 407.', 'normal', '', 2),
    LocationDef('Lab - Church Back Room - Ink Ribbon', 47003122, 'Lab Cable 2F', 'Ink Ribbon x3', 'Static record 409.', 'normal', '', 2),
    LocationDef('Lab - Church Back Room - Shotgun Ammo', 47003123, 'Lab Cable 2F', 'Shotgun Ammo x7', 'Static record 410.', 'normal', '', 2),
    LocationDef('Lab - Church Back Room - Napalm Grenades', 47003124, 'Lab Cable 2F', 'Napalm Grenades x6', 'Static record 411.', 'normal', '', 2),
    LocationDef('Lab - Leech Room - Leech Capsule', 47003125, 'Lab Start', 'Leech Capsule', 'Inventory-only cabinet interaction in room 110.', 'scripted', '', 2),
    LocationDef("Lab - Marcus's Study - Input Regulator Coil", 47003126, 'Lab Marcus', 'Input Regulator Coil', 'Inventory-only cabinet interaction in room 113.', 'scripted', '', 2),
    LocationDef('Factory - Platform - Green Herb 1', 47004100, 'Factory Start', 'Green Herb', 'Static record 412.', 'normal', '', 3),
    LocationDef('Factory - Platform - Green Herb 2', 47004101, 'Factory Start', 'Green Herb', 'Static record 413.', 'normal', '', 3),
    LocationDef('Factory - Maintenance Shaft - Magnum Ammo', 47004102, 'Factory Start', 'Magnum Ammo x8', 'Static record 417.', 'normal', '', 3),
    LocationDef('Factory - Maintenance Shaft - Handgun Ammo', 47004103, 'Factory Start', 'Handgun Ammo x15', 'Static record 418.', 'normal', '', 3),
    LocationDef('Factory - Maintenance Shaft - Green Herb', 47004104, 'Factory Start', 'Green Herb', 'Static record 419.', 'normal', '', 3),
    LocationDef('Factory - Maintenance Shaft - Red Herb', 47004105, 'Factory Start', 'Red Herb', 'Static record 420.', 'normal', '', 3),
    LocationDef('Factory - Turntable Platform - Elevator Key', 47004106, 'Factory Up', 'Elevator Key', 'Static record 425.', 'normal', '', 3),
    LocationDef('Factory - Turntable Monitor Room - Up Key', 47004107, 'Factory Start', 'Up Key', 'Static record 429.', 'normal', '', 3),
    LocationDef('Factory - Turntable Control Room - Ink Ribbon', 47004108, 'Factory Start', 'Ink Ribbon x3', 'Static record 430.', 'normal', '', 3),
    LocationDef('Factory - Turntable Control Room - Grenades', 47004109, 'Factory Start', 'Grenades x6', 'Static record 431.', 'normal', '', 3),
    LocationDef('Factory - Turntable Control Room - First-Aid Spray', 47004110, 'Factory Start', 'First-Aid Spray', 'Static record 432.', 'normal', '', 3),
    LocationDef('Factory - Turntable Control Room - Handgun Ammo', 47004111, 'Factory Start', 'Handgun Ammo x30', 'Static record 434.', 'normal', '', 3),
    LocationDef('Treatment Plant - Control Room - Ink Ribbon', 47005100, 'TP PreHandle', 'Ink Ribbon x3', 'Static record 439; room 142.', 'normal', '', 4),
    LocationDef('Treatment Plant - Air Regulator Room - Green Herb', 47005101, 'TP PreHandle', 'Green Herb', 'Static record 440; room 142.', 'normal', '', 4),
    LocationDef('Treatment Plant - Air Regulator Room - Red Herb', 47005102, 'TP PreHandle', 'Red Herb', 'Static record 441; room 142.', 'normal', '', 4),
    LocationDef('Treatment Plant - Control Room - Handgun Ammo', 47005103, 'TP PreHandle', 'Handgun Ammo x30', 'Static record 442; room 142.', 'normal', '', 4),
    LocationDef('Treatment Plant - Control Room - Gas Tank', 47005104, 'TP PreHandle', 'Gas Tank x6', 'Static record 443; room 142.', 'normal', '', 4),
    LocationDef('Treatment Plant - Air Regulator Room - Empty Bottle', 47005105, 'TP PreHandle', 'Empty Bottle x3', 'Static record 444; room 142.', 'normal', '', 4),
    LocationDef('Treatment Plant - Generator Room 2F - Green Herb 1', 47005106, 'TP PostHandle', 'Green Herb', 'Static record 447; room 143.', 'normal', '', 4),
    LocationDef('Treatment Plant - Generator Room 2F - Green Herb 2', 47005107, 'TP PostHandle', 'Green Herb', 'Static record 448; room 143.', 'normal', '', 4),
    LocationDef('Treatment Plant - Generator Room - Handgun Ammo', 47005108, 'TP PreHandle', 'Handgun Ammo x30', 'Static record 456; room 144.', 'normal', '', 4),
    LocationDef('Treatment Plant - Rec Room - Empty Bottle', 47005109, 'TP PreHandle', 'Empty Bottle x3', 'Static record 464; room 146.', 'normal', '', 4),
    LocationDef('Treatment Plant - Lodgings - Ink Ribbon', 47005110, 'TP PostHandle', 'Ink Ribbon x3', 'Static record 470; room 148.', 'normal', '', 4),
    LocationDef('Treatment Plant - Lodgings - First-Aid Spray', 47005111, 'TP PostHandle', 'First-Aid Spray', 'Static record 471; room 148.', 'normal', '', 4),
    LocationDef('Treatment Plant - Lodgings - Handgun Ammo', 47005112, 'TP PostHandle', 'Handgun Ammo x30', 'Static record 472; room 148.', 'normal', '', 4),
    LocationDef('Treatment Plant - Lodgings - Napalm Grenades', 47005113, 'TP PostHandle', 'Napalm Grenades x6', 'Static record 473; room 148.', 'normal', '', 4),
    LocationDef('Treatment Plant - Lodgings - Green Herb', 47005114, 'TP PostHandle', 'Green Herb', 'Static record 475; room 148.', 'normal', '', 4),
    LocationDef('Treatment Plant - Lodgings - Red Herb', 47005115, 'TP PostHandle', 'Red Herb', 'Static record 476; room 148.', 'normal', '', 4),
    LocationDef('Treatment Plant - Cargo Control Room - Shotgun Ammo', 47005116, 'TP PostHandle', 'Shotgun Ammo x7', 'Static record 513; room 152.', 'normal', '', 4),
    LocationDef('Treatment Plant - Maintenance Area - Keycard', 47005117, 'TP PreHandle', 'Keycard', 'Static record 515; room 153.', 'normal', '', 4),
    LocationDef('Treatment Plant - Maintenance Area - Green Herb', 47005118, 'TP PreHandle', 'Green Herb', 'Static record 516; room 153.', 'normal', '', 4),
    LocationDef('Treatment Plant - Maintenance Area - Red Herb', 47005119, 'TP PreHandle', 'Red Herb', 'Static record 517; room 153.', 'normal', '', 4),
    LocationDef('Treatment Plant - Water Pool - Handle', 47005120, 'TP PreHandle', 'Handle', 'Static record 519; room 154.', 'normal', '', 4),
    LocationDef('Treatment Plant - Water Pool - Shotgun Ammo', 47005121, 'TP PreHandle', 'Shotgun Ammo x7', 'Static record 520; room 154.', 'normal', '', 4),
    LocationDef('Treatment Plant - Laboratory - Industrial Water', 47005122, 'TP PostMotherboard', 'Industrial Water', 'Static record 558; room 157.', 'normal', '', 4),
    LocationDef('Treatment Plant - Laboratory - Acid Grenades', 47005123, 'TP PostMotherboard', 'Acid Grenades x6', 'Static record 559; room 157.', 'normal', '', 4),
    LocationDef('Treatment Plant - Floodgate Control Room - Acid Grenades', 47005124, 'TP PostMotherboard', 'Acid Grenades x6', 'Static record 560; room 158.', 'normal', '', 4),
    LocationDef('Treatment Plant - Water Treatment Walkway - Motherboard', 47005125, 'TP PostHandle', 'Motherboard', 'Static record 561; room 159.', 'normal', '', 4),
    LocationDef('Treatment Plant - Laboratory Cryo Room - Empty Battery', 47005126, 'TP PostMotherboard', 'Empty Battery', 'Static record 565; room 161.', 'normal', '', 4),
    LocationDef('Treatment Plant - Engine Room - Shotgun Ammo', 47005127, 'TP PostMotherboard', 'Shotgun Ammo x7', 'Static record 569; room 162.', 'normal', '', 4),
    LocationDef('Treatment Plant - Engine Room - Handgun Ammo', 47005128, 'TP PostMotherboard', 'Handgun Ammo x15', 'Static record 570; room 162.', 'normal', '', 4),
    LocationDef('Treatment Plant - Dam - Green Herb 1', 47005129, 'TP PostMotherboard', 'Green Herb', 'Static record 572; room 163.', 'normal', '', 4),
    LocationDef('Treatment Plant - Dam - Green Herb 2', 47005130, 'TP PostMotherboard', 'Green Herb', 'Static record 573; room 163.', 'normal', '', 4),
    LocationDef('Treatment Plant - Incinerator - Magnum Ammo', 47005131, 'TP Final', 'Magnum Ammo x8', 'Static record 577; room 164.', 'normal', '', 4),
    LocationDef('Treatment Plant - Storage - Ink Ribbon', 47005132, 'TP Final', 'Ink Ribbon x3', 'Static record 579; room 173.', 'normal', '', 4),
    LocationDef('Treatment Plant - Storage - Green Herb', 47005133, 'TP Final', 'Green Herb', 'Static record 580; room 173.', 'normal', '', 4),
    LocationDef('Treatment Plant - Storage - Red Herb', 47005134, 'TP Final', 'Red Herb', 'Static record 581; room 173.', 'normal', '', 4),
    LocationDef('Treatment Plant - Storage - Handgun Ammo', 47005135, 'TP Final', 'Handgun Ammo x30', 'Static record 582; room 173.', 'normal', '', 4),
    LocationDef('Treatment Plant - Storage - Shotgun Ammo', 47005136, 'TP Final', 'Shotgun Ammo x7', 'Static record 583; room 173.', 'normal', '', 4),
    LocationDef('Treatment Plant - Storage - Grenades', 47005137, 'TP Final', 'Grenades x6', 'Static record 584; room 173.', 'normal', '', 4),
    LocationDef('Treatment Plant - Storage - First-Aid Spray 1', 47005138, 'TP Final', 'First-Aid Spray', 'Static record 585; room 173.', 'normal', '', 4),
    LocationDef('Treatment Plant - Storage - First-Aid Spray 2', 47005139, 'TP Final', 'First-Aid Spray', 'Static record 586; room 173.', 'normal', '', 4),
    LocationDef('Treatment Plant - Fenced Area - Magnum Ammo', 47005140, 'TP Final', 'Magnum Ammo x8', 'Static record 588; room 174.', 'normal', '', 4),
]

ITEM_DEFS = [
    ItemDef('Handgun Ammo x15', 47000000, 21, 'filler', None, ''),
    ItemDef('Handgun Ammo x30', 47000001, 8, 'filler', None, ''),
    ItemDef('Dining Car Key', 47000003, 1, 'progression', 0, ''),
    ItemDef('Ink Ribbon x3', 47000004, 15, 'filler', None, ''),
    ItemDef('Green Herb', 47000005, 26, 'useful', None, ''),
    ItemDef('Ink Ribbon x1', 47000006, 1, 'filler', None, ''),
    ItemDef('Red Herb', 47000007, 12, 'useful', None, ''),
    ItemDef('Briefcase', 47000008, 1, 'progression', 0, ''),
    ItemDef('Empty Bottle x3', 47000009, 10, 'filler', None, ''),
    ItemDef('Gold Ring', 47000010, 1, 'progression', 0, ''),
    ItemDef('First-Aid Spray', 47000011, 9, 'useful', None, ''),
    ItemDef('Shotgun Ammo x7', 47000012, 16, 'useful', None, ''),
    ItemDef('Gas Tank x3', 47000013, 2, 'filler', None, ''),
    ItemDef('Hookshot', 47000014, 1, 'progression', 0, ''),
    ItemDef('Panel Opener', 47000015, 1, 'progression', 0, ''),
    ItemDef('Ice Pick', 47000016, 1, 'progression', 0, ''),
    ItemDef('Hunting Gun', 47000017, 1, 'useful', None, ''),
    ItemDef('Knife', 47000018, 1, 'useful', None, ''),
    ItemDef('Jewelry Box', 47000019, 1, 'progression', 0, ''),
    ItemDef("Conductor's Key", 47000020, 1, 'progression', 0, ''),
    ItemDef('Gas Tank x6', 47000021, 5, 'filler', None, ''),
    ItemDef('Blue Herb', 47000022, 4, 'useful', None, ''),
    ItemDef('Handgun Ammo x5', 47000023, 1, 'filler', None, ''),
    ItemDef('Magnum Ammo x1', 47000024, 1, 'useful', None, ''),
    ItemDef('Magnum Ammo x8', 47000025, 4, 'useful', None, ''),
    ItemDef('Grenades x6', 47000026, 3, 'useful', None, ''),
    ItemDef('Napalm Grenades x6', 47000027, 3, 'useful', None, ''),
    ItemDef('Acid Grenades x6', 47000028, 3, 'useful', None, ''),
    ItemDef('Shotgun', 47000029, 1, 'useful', None, ''),
    ItemDef('Grenade Launcher', 47000030, 1, 'useful', None, ''),
    ItemDef('Lighter Fluid', 47000031, 1, 'progression', 1, ''),
    ItemDef('Black Statue', 47000032, 1, 'progression', 1, ''),
    ItemDef('Discipline Tablet', 47000033, 1, 'progression', 1, ''),
    ItemDef('Microfilm A', 47000034, 1, 'progression', 1, ''),
    ItemDef('Iron Needle', 47000035, 1, 'progression', 1, ''),
    ItemDef('Book of Good', 47000036, 1, 'progression', 1, ''),
    ItemDef('Microfilm B', 47000038, 1, 'progression', 1, ''),
    ItemDef('Book of Evil', 47000039, 1, 'progression', 1, ''),
    ItemDef('White Statue', 47000040, 1, 'progression', 1, ''),
    ItemDef('Obedience Tablet', 47000041, 1, 'progression', 1, ''),
    ItemDef('Battery', 47000042, 1, 'progression', 1, ''),
    ItemDef('Vise Handle', 47000043, 1, 'progression', 1, ''),
    ItemDef('Fire Key', 47000044, 1, 'progression', 1, ''),
    ItemDef('Unity Tablet', 47000045, 1, 'progression', 1, ''),
    ItemDef('Locker Key', 47000046, 1, 'progression', 1, ''),
    ItemDef('Water Key', 47000047, 1, 'progression', 1, ''),
    ItemDef('Duralumin Case', 47000048, 1, 'progression', 1, ''),
    ItemDef('Magnum', 47000049, 1, 'useful', None, ''),
    ItemDef('Leech Capsule', 47000050, 1, 'progression', 2, ''),
    ItemDef('Input Regulator Coil', 47000051, 1, 'progression', 2, ''),
    ItemDef('Output Regulator Coil', 47000052, 1, 'progression', 2, ''),
    ItemDef('Green Leech Charm', 47000053, 1, 'progression', 2, ''),
    ItemDef('Breeding Room Key', 47000055, 1, 'progression', 2, ''),
    ItemDef('Dial', 47000056, 1, 'progression', 2, ''),
    ItemDef('Up Key', 47000057, 1, 'progression', 3, ''),
    ItemDef('Elevator Key', 47000058, 1, 'progression', 3, ''),
    ItemDef('Keycard', 47000059, 1, 'progression', 4, ''),
    ItemDef('Handle', 47000060, 1, 'progression', 4, ''),
    ItemDef('Motherboard', 47000061, 1, 'progression', 4, ''),
    ItemDef('Industrial Water', 47000062, 1, 'progression', 4, ''),
    ItemDef('Empty Battery', 47000063, 1, 'progression', 4, ''),
]

REGIONS = ('Menu', 'Train Start', 'Dining / Service', 'Conductor Wing', 'Freight / Rear', 'Cabin 102', 'Engine Cab', 'Facility Early', 'Facility Fire', 'Facility Crank', 'Facility Clock', 'Facility MO', 'Facility Library', 'Facility Basement', 'Facility Water', 'Facility Goal', 'Lab Start', 'Lab Marcus', 'Lab Morgue', 'Lab Sterile', 'Lab Breeding', 'Lab Machine', 'Lab Cable 2F', 'Factory Start', 'Factory Up', 'Factory End', 'TP PreHandle', 'TP PostHandle', 'TP PostMotherboard', 'TP Final', 'Victory')
REGION_CONNECTIONS = [('Menu', 'Train Start', ()), ('Train Start', 'Dining / Service', ('Dining Car Key',)), ('Train Start', 'Conductor Wing', ('Dining Car Key', "Conductor's Key")), ('Dining / Service', 'Freight / Rear', ('Ice Pick', 'Panel Opener')), ('Freight / Rear', 'Cabin 102', ('Hookshot',)), ('Cabin 102', 'Engine Cab', ('Briefcase', 'Gold Ring', 'Jewelry Box')), ('Engine Cab', 'Facility Early', ()), ('Facility Early', 'Facility Fire', ('Fire Key',)), ('Facility Early', 'Facility Crank', ()), ('Facility Crank', 'Facility Clock', ('Iron Needle',)), ('Facility Clock', 'Facility MO', ('Microfilm A', 'Microfilm B')), ('Facility Fire', 'Facility Library', ('Lighter Fluid',)), ('Facility Early', 'Facility Basement', ('Book of Good', 'Book of Evil', 'White Statue', 'Black Statue')), ('Facility Basement', 'Facility Water', ('Water Key',)), ('Facility Early', 'Facility Goal', ('Microfilm A', 'Microfilm B', 'Unity Tablet', 'Obedience Tablet', 'Discipline Tablet')), ('Facility Goal', 'Lab Start', ()), ('Lab Start', 'Lab Marcus', ('Leech Capsule',)), ('Lab Marcus', 'Lab Morgue', ('Green Leech Charm',)), ('Lab Morgue', 'Lab Sterile', ()), ('Lab Sterile', 'Lab Breeding', ('Breeding Room Key',)), ('Lab Breeding', 'Lab Machine', ('Dial',)), ('Lab Machine', 'Lab Cable 2F', ('Input Regulator Coil', 'Output Regulator Coil')), ('Lab Cable 2F', 'Factory Start', ()), ('Factory Start', 'Factory Up', ('Up Key',)), ('Factory Up', 'Factory End', ('Elevator Key',)), ('Factory End', 'TP PreHandle', ()), ('TP PreHandle', 'TP PostHandle', ('Handle',)), ('TP PostHandle', 'TP PostMotherboard', ('Motherboard',)), ('TP PostMotherboard', 'TP Final', ('Keycard',)), ('TP Final', 'Victory', ())]
LOCATION_REQUIREMENTS = {'Train - Bar Lounge - Panel Opener': ('Ice Pick',), 'Train - Dining Car - Empty Bottle': ('Panel Opener',), 'Facility - Entrance - Discipline Tablet': ('Battery',), 'Facility - Maintenance Room - Obedience Tablet': ('Vise Handle',), 'Basement - Bunk Room A - Unity Tablet': ('Lighter Fluid',), 'Basement - Bunk Room A - Empty Bottle': ('Lighter Fluid',), 'Basement - Training Room - Duralumin Case': ('Locker Key',), 'Treatment Plant - Maintenance Area - Keycard': ('Empty Battery', 'Industrial Water')}
FORCED_PLACEMENTS = {}
GOAL_LOCATION = 'RE0 - Defeat Queen Leech'
GOAL_ITEM = 'Queen Leech Defeated'
FIRE_KEY_LOCATION = 'Facility - Large Hall - Fire Key'
FIRE_KEY_SAFE_FILLER = {'Ink Ribbon x1', 'Handgun Ammo x15', 'Acid Grenades x6', 'Blue Herb', 'Gas Tank x3', 'First-Aid Spray', 'Shotgun Ammo x7', 'Grenades x6', 'Empty Bottle x3', 'Ink Ribbon x3', 'Napalm Grenades x6', 'Green Herb', 'Gas Tank x6', 'Red Herb', 'Handgun Ammo x30', 'Magnum Ammo x8', 'Handgun Ammo x5', 'Magnum Ammo x1'}
HANDLE_SAFE_LOCATIONS = {'Treatment Plant - Water Pool - Shotgun Ammo', 'Treatment Plant - Air Regulator Room - Green Herb', 'Treatment Plant - Maintenance Area - Red Herb', 'Treatment Plant - Rec Room - Empty Bottle', 'Treatment Plant - Air Regulator Room - Empty Bottle', 'Treatment Plant - Control Room - Ink Ribbon', 'Treatment Plant - Control Room - Handgun Ammo', 'Treatment Plant - Air Regulator Room - Red Herb', 'Treatment Plant - Water Pool - Handle', 'Treatment Plant - Control Room - Gas Tank', 'Treatment Plant - Maintenance Area - Green Herb'}
